name: intent_to_kill
description: "Intent to kill"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.6
  easy_localization: ^3.0.7
  shared_preferences: ^2.1.0
  auto_size_text: any
  in_app_review: ^2.0.10

  qoiu_utils:
    git:
      url:  https://github.com/qoiu/flutter_libs
      path: qoiu_utils

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0



  flutter_launcher_icons: any

#flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: 'ic_launcher'
  ios: true
  image_path: "assets/char/ptrl.jpg"

flutter:
  generate: true

  uses-material-design: true
  assets:
    - assets/char/
    - assets/class/
    - assets/motive/
    - assets/icon/
    - assets/images/
    - assets/translate/
    - assets/scenario/

