import 'package:intent_to_kill/enum/classes.dart';

enum KillerCharacter {
  actr(KillerClass.boh),
  agnt(KillerClass.rule),
  ambas(KillerClass.rule),
  artist(KillerClass.boh),
  bart(KillerClass.crime),
  basb(KillerClass.boh),
  briolin(KillerClass.marg),
  catw(KillerClass.marg),
  congr(KillerClass.rule),
  coro(KillerClass.med),
  dict(KillerClass.press),
  disp(KillerClass.law),
  dncr(KillerClass.marg),
  don(KillerClass.crime),
  dorm(KillerClass.crime),
  driver(KillerClass.work),
  edit(KillerClass.press),
  fila(KillerClass.boh),
  fire(KillerClass.work),
  fortn(KillerClass.imm),
  gangstr(KillerClass.crime),
  homls(KillerClass.marg),
  iccrm(KillerClass.work),
  inform(KillerClass.crime),
  inspctr(KillerClass.law),
  jrnlst(KillerClass.press),
  judg(KillerClass.law),
  lawr(KillerClass.law),
  libr(KillerClass.press),
  lobb(KillerClass.rule),
  mayr(KillerClass.rule),
  monc(KillerClass.imm),
  muzic(KillerClass.imm),
  nurf(KillerClass.med),
  nurm(KillerClass.med),
  nwsp(KillerClass.press),
  pharm(KillerClass.med),
  phto(KillerClass.press),
  post(KillerClass.work),
  prof(KillerClass.imm),
  prosec(KillerClass.law),
  psych(KillerClass.boh),
  ptrl(KillerClass.law),
  rest(KillerClass.boh),
  sail(KillerClass.imm),
  secr(KillerClass.rule),
  spclnt(KillerClass.crime),
  stew(KillerClass.imm),
  surg(KillerClass.med),
  vet(KillerClass.marg),
  wait(KillerClass.work),
  wdow(KillerClass.marg),
  weld(KillerClass.work),
  wete(KillerClass.med);

  const KillerCharacter(this.kClass);
  final KillerClass kClass;
}
